/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaMain */

#ifndef _Included_JavaMain
#define _Included_JavaMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaMain
 * Method:    triggerCAddTask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JavaMain_triggerCAddTask
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
